site_name: "Conan Toolchain Build System"
copyright: Copyright © 2025, David L. Armstrong. All rights reserved.
repo_url: https://github.com/DaverSomethingSomethingOrg/ConanToolchain
site_url: https://github.com/DaverSomethingSomethingOrg/ConanToolchain
#edit_uri_template: 'edit/main/docs/{path}'
docs_dir: docs/

extra:
  version:
    provider: mike

plugins:
  - techdocs-core
#   - mkdocstrings:
#       default_handler: python
#       handlers:
#         python:
#           paths: [src]
#           options:
# #            inherited_members: true
#             filters:
#               - "!^__"

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer

markdown_extensions:
  - toc:
      permalink: '#'
      toc_depth: 4
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts

watch:
  - docs/
  - src/

nav:
  - 'index.md'
  - 'SampleUsage.md'
  - 'ConanRecipePreReqs.md'
  - 'ConanCustomDeployer.md'
  - 'RPMPackageGen.md'
